# Generated by Django 3.0.3 on 2020-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplystart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='address1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_filename',
            field=models.FileField(blank=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='zipcode',
            field=models.DecimalField(decimal_places=0, default=45220, max_digits=5),
        ),
    ]
